version: '3'
services:
  nginx: 
    image : nginx:latest 
    ports : 
        - 8000:8000
        - 8443:8443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./certs/localhost.crt:/etc/nginx/certs/localhost.crt
      - ./certs/localhost.decrypted.key:/etc/nginx/certs/localhost.key
    networks:
      - brewhouse-manager-net
    depends_on:
      - "web"
  web:
    image: brewhouse-manager:dev
    expose:
      - 5000
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_REGION=${AWS_REGION}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    env_file:
      - ./docker-local.env
      - ".env"
    depends_on:
      postgres:
        condition: service_healthy
      db-data-seed:
        condition: service_completed_successfully
    networks:
      - brewhouse-manager-net
    volumes:
      - ./my-config.json:/brewhouse-manager/config/config.json
      - ./uploads:/brewhouse-manager/api/static/assets/uploads
    stdin_open: true
    tty: true
  postgres:
    image: postgres:17-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - brewhouse-manager-net
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./docker-local.env
      - ".env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
  db-data-seed:
    image: brewhouse-manager-db-seed:dev
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./docker-local.env
      - ".env"
    volumes:
      - ./my-config.json:/brewhouse-manager/config/config.json
    networks:
      - brewhouse-manager-net
networks:
  brewhouse-manager-net:
      