version: '2'
services:
  nginx: 
    image : nginx:latest 
    ports : 
        - 5000:5000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./certs/localhost.crt:/etc/nginx/certs/localhost.crt
      - ./certs/localhost.decrypted.key:/etc/nginx/certs/localhost.key
    networks:
      - brewhouse-manager-net
    depends_on:
      - "web"
  web:
    image: brewhouse-manager:dev
    expose:
      - 5000
    environment:
      - CONFIG_PATH=config.json
    env_file:
      - ./docker-local.env
      - ".env"
    depends_on:
      - postgres
      - db-data-seed
    networks:
      - brewhouse-manager-net
    volumes:
      - ./my-config.json:/brewhouse-manager/config/config.json
    stdin_open: true
    tty: true
  postgres:
    image: postgres:12-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - brewhouse-manager-net
    volumes:
      - ./my-config.json:/brewhouse-manager/config/config.json
    env_file:
      - ./docker-local.env
      - ".env"
  db-data-seed:
    image: brewhouse-manager-db-seed:dev
    depends_on:
      - postgres
    env_file:
      - ./docker-local.env
      - ".env"
    networks:
      - brewhouse-manager-net
networks:
  brewhouse-manager-net:
      