"""add-brewery-column-to-beers

Revision ID: 40ce43732aef
Revises: a684c1ffb776
Create Date: 2022-05-13 14:52:25.840351+01:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "40ce43732aef"
down_revision = "a684c1ffb776"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("beers", sa.Column("brewery", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("beers", "brewery")
    # ### end Alembic commands ###
