"""remove-tap-type-column-from-tap-table

Revision ID: 902b4fc409a7
Revises: a4025c379532
Create Date: 2022-05-13 15:18:14.434985+01:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "902b4fc409a7"
down_revision = "a4025c379532"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("taps", sa.Column("beverage_id", postgresql.UUID(), nullable=True))
    op.create_index("ix_taps_beverage_id", "taps", ["beverage_id"], unique=False)
    op.create_foreign_key(None, "taps", "beverages", ["beverage_id"], ["id"])
    op.drop_column("taps", "tap_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("taps", sa.Column("tap_type", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "taps", type_="foreignkey")
    op.drop_index("ix_taps_beverage_id", table_name="taps")
    op.drop_column("taps", "beverage_id")
    # ### end Alembic commands ###
