"""Add API key to users table

Revision ID: d3fb27e0ae7d
Revises: 14586261b180
Create Date: 2022-10-21 21:58:29.804457+01:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d3fb27e0ae7d"
down_revision = "14586261b180"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("api_key", sa.String(), nullable=True))
    op.create_index("ix_user_api_key", "users", ["api_key"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_api_key", table_name="users")
    op.drop_column("users", "api_key")
    # ### end Alembic commands ###
