"""add-beer-and-beverage-image-transitions

Revision ID: 96c1bb772b2e
Revises: 6c0e4cf18c37
Create Date: 2022-10-04 14:59:09.331170+01:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "96c1bb772b2e"
down_revision = "6c0e4cf18c37"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_transitions",
        sa.Column("created_app", sa.String(), server_default=sa.text("current_setting('application_name')"), nullable=False),
        sa.Column("created_user", sa.String(), server_default=sa.text("CURRENT_USER"), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_app", sa.String(), server_default=sa.text("current_setting('application_name')"), nullable=False),
        sa.Column("updated_user", sa.String(), server_default=sa.text("CURRENT_USER"), nullable=False),
        sa.Column("updated_on", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("id", postgresql.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("beer_id", postgresql.UUID(), nullable=True),
        sa.Column("beverage_id", postgresql.UUID(), nullable=True),
        sa.Column("img_url", sa.String(), nullable=False),
        sa.Column("change_percent", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["beer_id"],
            ["beers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["beverage_id"],
            ["beverages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_image_transition_beer_id", "image_transitions", ["beer_id"], unique=False)
    op.create_index("ix_image_transition_beverage_id", "image_transitions", ["beverage_id"], unique=False)
    op.add_column("beers", sa.Column("empty_img_url", sa.String(), nullable=True))
    op.add_column("beers", sa.Column("image_transitions_enabled", sa.Boolean(), nullable=True))
    op.execute("UPDATE beers SET image_transitions_enabled = false")
    op.alter_column("beers", "image_transitions_enabled", nullable=False)
    op.add_column("beverages", sa.Column("empty_img_url", sa.String(), nullable=True))
    op.add_column("beverages", sa.Column("image_transitions_enabled", sa.Boolean(), nullable=True))
    op.execute("UPDATE beverages SET image_transitions_enabled = false")
    op.alter_column("beverages", "image_transitions_enabled", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("beverages", "image_transitions_enabled")
    op.drop_column("beverages", "empty_img_url")
    op.drop_column("beers", "image_transitions_enabled")
    op.drop_column("beers", "empty_img_url")
    op.drop_index("ix_image_transition_beverage_id", table_name="image_transitions")
    op.drop_index("ix_image_transition_beer_id", table_name="image_transitions")
    op.drop_table("image_transitions")
    # ### end Alembic commands ###
