"""add-untappd-id-to-beer

Revision ID: 55e00c2955e5
Revises: d92ab9dc026d
Create Date: 2022-01-30 13:47:50.638690+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "55e00c2955e5"
down_revision = "d92ab9dc026d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("beers", sa.Column("untappd_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("beers", "untappd_id")
    # ### end Alembic commands ###
