"""add_beer_overrides_to_batches

Revision ID: e32a62bcc0f5
Revises: e2f049fb8d18
Create Date: 2024-09-04 16:53:55.007088+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32a62bcc0f5'
down_revision = 'e2f049fb8d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('abv', sa.Float(), nullable=True))
    op.add_column('batches', sa.Column('ibu', sa.Float(), nullable=True))
    op.add_column('batches', sa.Column('srm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'srm')
    op.drop_column('batches', 'ibu')
    op.drop_column('batches', 'abv')
    # ### end Alembic commands ###
