"""move-locations-to-batches

Revision ID: 3f4c02e5c260
Revises: d61884ad4009
Create Date: 2025-10-09 19:13:00.839515+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f4c02e5c260"
down_revision = "d61884ad4009"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch_locations",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("created_app", sa.String(), server_default=sa.text("current_setting('application_name')"), nullable=False),
        sa.Column("created_user", sa.String(), server_default=sa.text("CURRENT_USER"), nullable=False),
        sa.Column("created_on", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column("updated_app", sa.String(), server_default=sa.text("current_setting('application_name')"), nullable=False),
        sa.Column("updated_user", sa.String(), server_default=sa.text("CURRENT_USER"), nullable=False),
        sa.Column("updated_on", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_locations_batch_id", "batch_locations", ["batch_id"], unique=False)
    op.create_index("ix_locations_batch_id_location_id", "batch_locations", ["batch_id", "location_id"], unique=True)
    op.create_index("beer_name_lower_ix", "beers", [sa.text("lower(name)")], unique=True)

    op.execute("INSERT INTO batch_locations (batch_id, location_id) SELECT ba.id, be.location_id FROM batches ba JOIN beers be ON ba.beer_id = be.id")
    op.execute("INSERT INTO batch_locations (batch_id, location_id) SELECT ba.id, be.location_id FROM batches ba JOIN beverages be ON ba.beverage_id = be.id")

    op.drop_constraint("beers_location_id_fkey", "beers", type_="foreignkey")
    op.drop_column("beers", "location_id")
    op.create_index("beverage_name_lower_ix", "beverages", [sa.text("lower(name)")], unique=True)
    op.drop_constraint("beverages_location_id_fkey", "beverages", type_="foreignkey")
    op.drop_column("beverages", "location_id")
    op.create_index("locations_name_lower_ix", "locations", [sa.text("lower(name)")], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("locations_name_lower_ix", table_name="locations")
    op.add_column("beverages", sa.Column("location_id", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key("beverages_location_id_fkey", "beverages", "locations", ["location_id"], ["id"])
    op.drop_index("beverage_name_lower_ix", table_name="beverages")
    op.add_column("beers", sa.Column("location_id", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key("beers_location_id_fkey", "beers", "locations", ["location_id"], ["id"])
    op.drop_index("beer_name_lower_ix", table_name="beers")
    op.drop_index("ix_locations_batch_id_location_id", table_name="batch_locations")
    op.drop_index("ix_locations_batch_id", table_name="batch_locations")
    op.drop_table("batch_locations")
    # ### end Alembic commands ###
