"""add-optional-name-and-image-url-to-batches

Revision ID: d61884ad4009
Revises: e3d0e743d284
Create Date: 2025-08-24 20:50:58.054308+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61884ad4009'
down_revision = 'e3d0e743d284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('name', sa.String(), nullable=True))
    op.add_column('batches', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'img_url')
    op.drop_column('batches', 'name')
    # ### end Alembic commands ###
