"""add-plaato-data-table

Revision ID: 08ffd519fbca
Revises: 590b713a55d1
Create Date: 2026-02-01 01:44:14.049072+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ffd519fbca'
down_revision = '590b713a55d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaato_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('last_pour_string', sa.String(), nullable=True),
    sa.Column('percent_of_beer_left', sa.String(), nullable=True),
    sa.Column('is_pouring', sa.String(), nullable=True),
    sa.Column('amount_left', sa.String(), nullable=True),
    sa.Column('temperature_offset', sa.String(), nullable=True),
    sa.Column('keg_temperature', sa.String(), nullable=True),
    sa.Column('last_pour', sa.String(), nullable=True),
    sa.Column('tare', sa.String(), nullable=True),
    sa.Column('known_weight_calibrate', sa.String(), nullable=True),
    sa.Column('empty_keg_weight', sa.String(), nullable=True),
    sa.Column('beer_style', sa.String(), nullable=True),
    sa.Column('og', sa.String(), nullable=True),
    sa.Column('fg', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('calculated_abv', sa.String(), nullable=True),
    sa.Column('keg_temperature_string', sa.String(), nullable=True),
    sa.Column('calculated_alcohol_string', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('calculate', sa.String(), nullable=True),
    sa.Column('beer_left_unit', sa.String(), nullable=True),
    sa.Column('measure_unit', sa.String(), nullable=True),
    sa.Column('max_keg_volume', sa.String(), nullable=True),
    sa.Column('temperature_unit', sa.String(), nullable=True),
    sa.Column('wifi_signal_strength', sa.String(), nullable=True),
    sa.Column('volume_unit', sa.String(), nullable=True),
    sa.Column('leak_detection', sa.String(), nullable=True),
    sa.Column('min_temperature', sa.String(), nullable=True),
    sa.Column('max_temperature', sa.String(), nullable=True),
    sa.Column('keg_mode_c02_beer', sa.String(), nullable=True),
    sa.Column('sensitivity', sa.String(), nullable=True),
    sa.Column('chip_temperature_string', sa.String(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('last_updated_on', sa.Date(), nullable=True),
    sa.Column('created_app', sa.String(), server_default=sa.text("current_setting('application_name')"), nullable=False),
    sa.Column('created_user', sa.String(), server_default=sa.text('CURRENT_USER'), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_app', sa.String(), server_default=sa.text("current_setting('application_name')"), nullable=False),
    sa.Column('updated_user', sa.String(), server_default=sa.text('CURRENT_USER'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plaato_data')
    # ### end Alembic commands ###
