"""add user override columsn to plaato_data

Revision ID: 91f0f225f0aa
Revises: 8a2b3c4d5e6f
Create Date: 2026-02-05 22:12:15.506883+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f0f225f0aa'
down_revision = '8a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaato_data', sa.Column('user_keg_mode_c02_beer', sa.String(), nullable=True))
    op.add_column('plaato_data', sa.Column('user_unit', sa.String(), nullable=True))
    op.add_column('plaato_data', sa.Column('user_measure_unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaato_data', 'user_measure_unit')
    op.drop_column('plaato_data', 'user_unit')
    op.drop_column('plaato_data', 'user_keg_mode_c02_beer')
    # ### end Alembic commands ###
