"""Remove fermentation controller tables

Revision ID: 590b713a55d1
Revises: 3f4c02e5c260
Create Date: 2026-02-01 01:10:48.332483+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '590b713a55d1'
down_revision = '3f4c02e5c260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fermentation_controller_stats_parent_id'), table_name='fermentation_controller_stats')
    op.drop_table('fermentation_controller_stats')
    op.drop_index(op.f('ix_unique_manufacturer_manufacturer_id_model'), table_name='fermentation_controller')
    op.drop_table('fermentation_controller')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fermentation_controller_stats',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('fermentation_controller_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fermentation_controller_id'], ['fermentation_controller.id'], name=op.f('fermentation_controller_stats_fermentation_controller_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fermentation_controller_stats_pkey'))
    )
    op.create_index(op.f('ix_fermentation_controller_stats_parent_id'), 'fermentation_controller_stats', ['fermentation_controller_id'], unique=False)
    op.create_table('fermentation_controller',
    sa.Column('created_app', sa.VARCHAR(), server_default=sa.text("current_setting('application_name'::text)"), autoincrement=False, nullable=False),
    sa.Column('created_user', sa.VARCHAR(), server_default=sa.text('CURRENT_USER'), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_app', sa.VARCHAR(), server_default=sa.text("current_setting('application_name'::text)"), autoincrement=False, nullable=False),
    sa.Column('updated_user', sa.VARCHAR(), server_default=sa.text('CURRENT_USER'), autoincrement=False, nullable=False),
    sa.Column('updated_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('manufacturer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('calibration_differential', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature_precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cooling_differential', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('heating_differential', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('program', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fermentation_controller_pkey'))
    )
    op.create_index(op.f('ix_unique_manufacturer_manufacturer_id_model'), 'fermentation_controller', ['manufacturer_id', 'manufacturer', 'model'], unique=True)
    # ### end Alembic commands ###
